### ISSUE TITLE
Project generator could create a bit nicer unique component aliases

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-rest#630]
Our component aliases currently contain connectionId, which is not too user friendly (for example `twitter-mention-connector--KuYUr3kEMhDH0Nq8VGV`). We could generate aliases by following two simple rules
 - for components that do not occur more than once, don't use aliases
 - for components that occur more than once use a per component counter

This should lead to component aliases that look something like this in the generated `syndesis.yml`:

```yml

---
flows:
- steps:
  - kind: endpoint
    uri: twitter-mention-connector:MENTIONS
  - kind: endpoint
    uri: atlas:mapping-step-2.json
  - kind: endpoint
uri: salesforce-upsert-sobject-1?sObjectIdName=TwitterScreenName__c&sObjectName=Contact
  - kind: endpoint
uri: salesforce-upsert-sobject-2?sObjectIdName=TwitterScreenName__c&sObjectName=Opportunity
```
