### ISSUE TITLE
Sanitize generated integration ID to respect URI standard

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-rest#660]
There's a chance that generated ID contains URI illegal character like underscore from the example below. That eventually results in runtime exception.

https://tools.ietf.org/html/rfc3986#page-17
  
```yaml
---
flows:
- steps:
  - kind: endpoint
    uri: twitter-mention-connector--KvRgCGge2Kbbkcn_p-2:MENTIONS
  - kind: endpoint
    uri: atlas:mapping-step-2.json
  - kind: endpoint
    uri: salesforce-upsert-sobject--KvRfIZye2Kbbkcn_p-1?sObjectIdName=TwitterScreenName__c&sObjectName=Contact
```
