### ISSUE TITLE
Limits in Integrations's DC seems to be missing unit

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-rest#713]
@rhuss this doesn't seem ok also OpenShift is complaining when there is no unit used.

```
    resources:
      limits:
        memory: '512'
      requests:
        memory: '200'
```
